from collections import OrderedDict

# ────────────────────────── TAXONOMY ────────────────────────────
# Ordered so the first hit "wins" when multiple keywords appear
SUB_INDUSTRY_KEYWORDS: "OrderedDict[str, tuple[str,list[str]]]" = OrderedDict([
    # Tech & AI  (20)
    ("SaaS",             ("Tech & AI", ["saas", "subscription software"])),
    ("Cloud Computing",  ("Tech & AI", ["cloud", "aws", "azure", "gcp"])),
    ("Cyber Security",   ("Tech & AI", ["cybersecurity", "firewall", "antivirus", "infosec"])),
    ("E-Commerce Tech",  ("Tech & AI", ["e-commerce platform", "shopify", "woocommerce"])),
    ("Blockchain",       ("Tech & AI", ["blockchain", "web3", "ethereum", "bitcoin"])),
    ("FinTech Stack",    ("Tech & AI", ["payment gateway", "stripe api", "banking-as-a-service"])),
    ("EdTech",           ("Tech & AI", ["edtech", "learning management system", "lms"])),
    ("MarTech",          ("Tech & AI", ["marketing automation", "crm", "hubspot"])),
    ("HR Tech",          ("Tech & AI", ["hr software", "talent platform", "ats"])),
    ("PropTech",         ("Tech & AI", ["proptech", "real-estate tech"])),
    ("Health IT",        ("Tech & AI", ["ehr", "emr", "telehealth", "medtech software"])),
    ("AI LLM",           ("Tech & AI", ["ai", "machine learning", "deep learning", "llm"])),
    ("Robotics",         ("Tech & AI", ["robotics", "autonomous", "drone"])),
    ("IoT",              ("Tech & AI", ["iot device", "internet of things"])),
    ("AR / VR",          ("Tech & AI", ["augmented reality", "virtual reality", "metaverse"])),
    ("Analytics",        ("Tech & AI", ["data analytics", "business intelligence", "bi tool"])),
    ("DevOps",           ("Tech & AI", ["ci/cd", "kubernetes", "devops"])),
    ("Gaming",           ("Tech & AI", ["game studio", "game development", "gaming platform"])),
    ("AdTech",           ("Tech & AI", ["ad network", "programmatic ads"])),
    ("General Software", ("Tech & AI", ["software development", "custom software"])),
    # Finance & Fintech (20)
    ("Neo Bank",         ("Finance & Fintech", ["neobank", "digital bank"])),
    ("Payment Gateway",  ("Finance & Fintech", ["payment gateway", "merchant services"])),
    ("Lending Platform", ("Finance & Fintech", ["p2p lending", "loan platform", "mortgage tech"])),
    ("Wealth Tech",      ("Finance & Fintech", ["wealth management", "robo-advisor"])),
    ("InsurTech",        ("Finance & Fintech", ["insurtech", "insurance platform"])),
    ("Accounting SaaS",  ("Finance & Fintech", ["accounting software", "bookkeeping platform"])),
    ("Crypto Exchange",  ("Finance & Fintech", ["crypto exchange", "defi", "dex"])),
    ("RegTech",          ("Finance & Fintech", ["regtech", "kyc", "aml"])),
    ("Payroll Tech",     ("Finance & Fintech", ["payroll software", "salary management"])),
    ("Point-of-Sale",    ("Finance & Fintech", ["pos system", "point of sale"])),
    ("Trading Platform", ("Finance & Fintech", ["trading platform", "brokerage"])),
    ("Tax Software",     ("Finance & Fintech", ["tax software", "tax filing"])),
    ("Expense Mgmt",     ("Finance & Fintech", ["expense management", "spend control"])),
    ("Invoice Factoring",("Finance & Fintech", ["invoice factoring", "receivables finance"])),
    ("Crowdfunding",     ("Finance & Fintech", ["crowdfunding", "kickstarter-like"])),
    ("Billing API",      ("Finance & Fintech", ["recurring billing", "stripe"])),
    ("Financial Data API",("Finance & Fintech",["open banking api", "plaid"])),
    ("Treasury Mgmt",    ("Finance & Fintech", ["treasury management", "cash management"])),
    ("ATM / Kiosk",      ("Finance & Fintech", ["atm network", "bank kiosk"])),
    ("Angel Network",    ("Finance & Fintech", ["angel network", "venture funding"])),
    # Health & Wellness (20)
    ("Hospital",         ("Health & Wellness", ["hospital", "clinic", "medical center"])),
    ("Telemedicine",     ("Health & Wellness", ["telemedicine", "telehealth"])),
    ("Mental Health App",("Health & Wellness", ["mental health app", "therapy app"])),
    ("Fitness Studio",   ("Health & Wellness", ["gym", "fitness center", "crossfit"])),
    ("Yoga Studio",      ("Health & Wellness", ["yoga studio", "pilates studio"])),
    ("Wellness Product", ("Health & Wellness", ["supplements", "nutraceutical"])),
    ("Pharma Company",   ("Health & Wellness", ["pharmaceutical", "drug discovery"])),
    ("Biotech",          ("Health & Wellness", ["biotech", "gene therapy"])),
    ("Medical Device",   ("Health & Wellness", ["medical device", "diagnostic device"])),
    ("Dental Clinic",    ("Health & Wellness", ["dental clinic", "dentist"])),
    ("EHR Vendor",       ("Health & Wellness", ["ehr", "emr platform"])),
    ("Health Insurance", ("Health & Wellness", ["health insurance", "payer"])),
    ("Nutrition Coaching",("Health & Wellness",["nutrition coach", "dietician"])),
    ("Spa / Wellness",   ("Health & Wellness", ["spa", "wellness retreat"])),
    ("Life Sciences",    ("Health & Wellness", ["life sciences", "clinical trial"])),
    ("Child Care",       ("Health & Wellness", ["childcare center", "daycare"])),
    ("Senior Care",      ("Health & Wellness", ["senior care", "assisted living"])),
    ("Sports Medicine",  ("Health & Wellness", ["sports medicine", "physiotherapy"])),
    ("Pet Health",       ("Health & Wellness", ["veterinary", "pet clinic"])),
    ("Healthcare Consulting",("Health & Wellness",["healthcare consulting"])),
    # Media & Education (20)
    ("University",       ("Media & Education", ["university", "college", "campus"])),
    ("K-12 School",      ("Media & Education", ["k-12", "elementary school", "high school"])),
    ("Online Course",    ("Media & Education", ["online course", "mooc", "udemy"])),
    ("Publishing House", ("Media & Education", ["publisher", "publishing house"])),
    ("News Outlet",      ("Media & Education", ["news", "newspaper", "magazine"])),
    ("Streaming Media",  ("Media & Education", ["streaming", "ott platform", "vod"])),
    ("Podcast Network",  ("Media & Education", ["podcast network", "podcasting"])),
    ("Marketing Agency", ("Media & Education", ["marketing agency", "advertising agency"])),
    ("Social Network",   ("Media & Education", ["social network", "social media platform"])),
    ("Gaming Studio",    ("Media & Education", ["game studio", "game publisher"])),
    ("Bookstore",        ("Media & Education", ["bookstore", "library"])),
    ("Language Learning",("Media & Education", ["language learning", "duolingo"])),
    ("Ed-Publishing",    ("Media & Education", ["educational publishing"])),
    ("E-Learning SaaS",  ("Media & Education", ["learning management system", "lms"])),
    ("PR Agency",        ("Media & Education", ["public relations", "pr agency"])),
    ("Photo Stock",      ("Media & Education", ["stock photos", "photo marketplace"])),
    ("Video Production", ("Media & Education", ["video production", "film studio"])),
    ("Music Label",      ("Media & Education", ["music label", "record label"])),
    ("Ticketing Platform",("Media & Education",["ticketing platform", "event tickets"])),
    ("e-Sports Org",     ("Media & Education", ["esports", "competitive gaming"])),
    # Energy & Industry (20)
    ("Solar Installer",  ("Energy & Industry", ["solar installer", "pv system"])),
    ("Wind Energy",      ("Energy & Industry", ["wind farm", "wind turbine"])),
    ("Oil & Gas",        ("Energy & Industry", ["oil field", "drilling", "refinery"])),
    ("Battery Tech",     ("Energy & Industry", ["battery technology", "lithium-ion"])),
    ("EV Charging",      ("Energy & Industry", ["ev charging", "charging station"])),
    ("Nuclear Energy",   ("Energy & Industry", ["nuclear power", "reactor"])),
    ("Water Utility",    ("Energy & Industry", ["water utility", "water treatment"])),
    ("Waste Management", ("Energy & Industry", ["waste management", "recycling"])),
    ("Manufacturing",    ("Energy & Industry", ["manufacturing", "factory"])),
    ("Logistics",        ("Energy & Industry", ["logistics", "supply chain"])),
    ("Aerospace",        ("Energy & Industry", ["aerospace", "space systems"])),
    ("Automotive",       ("Energy & Industry", ["automotive", "car manufacturer"])),
    ("Agritech",         ("Energy & Industry", ["agritech", "precision agriculture"])),
    ("Chemical Plant",   ("Energy & Industry", ["chemical plant", "chemicals"])),
    ("Mining",           ("Energy & Industry", ["mining", "mineral extraction"])),
    ("Construction",     ("Energy & Industry", ["construction", "civil engineering"])),
    ("HVAC Services",    ("Energy & Industry", ["hvac", "heating cooling"])),
    ("Packaging",        ("Energy & Industry", ["packaging", "labeling"])),
    ("Textiles",         ("Energy & Industry", ["textile mill", "fabric manufacturer"])),
    ("3D Printing",      ("Energy & Industry", ["3d printing", "additive manufacturing"])),
])

# ───────────────────── New taxonomy utils ─────────────────────────────
ALLOWED_INDUSTRIES = [
    "Marketing", "Technology", "Finance", "Healthcare", "Manufacturing",
    "Retail", "Education", "Real Estate", "Energy & Utilities",
    "Transportation & Logistics", "Media & Entertainment",
]

_LEGACY_TO_NEW = {
    "Tech & AI": "Technology",
    "Finance & Fintech": "Finance",
    "Health & Wellness": "Healthcare",
    "Media & Education": "Media & Entertainment",
    "Energy & Industry": "Energy & Utilities",
}

# ----------------- updated keyword heuristic -------------------------
INDUSTRY_KEYWORDS = {
    "marketing":        "Marketing",
    "advertising":      "Marketing",
    "seo":              "Marketing",
    "saas":             "Technology",
    "software":         "Technology",
    "ai":               "Technology",
    "machine learning": "Technology",
    "blockchain":       "Finance",
    "crypto":           "Finance",
    "bank":             "Finance",
    "clinic":           "Healthcare",
    "hospital":         "Healthcare",
    "pharma":           "Healthcare",
    "fitness":          "Healthcare",
    "solar":            "Energy & Utilities",
    "oil":              "Energy & Utilities",
    "gas":              "Energy & Utilities",
    "manufacturing":    "Manufacturing",
    "retail":           "Retail",
    "e-commerce":       "Retail",
}

# New 11-sector taxonomy  ─────────────────────────────────────────────
KEYWORDS = {
    "marketing":      ["marketing", "advertising", "seo", "content", "campaign"],
    "technology":     ["software", "saas", "cloud", "ai", "machine learning"],
    "finance":        ["fintech", "payments", "bank", "crypto", "lending"],
    "healthcare":     ["health", "clinic", "medical", "pharma", "hospital"],
    "manufacturing":  ["manufacturing", "industrial", "factory", "automation"],
    "retail":         ["retail", "e-commerce", "store", "consumer"],
    "education":      ["edtech", "school", "university", "training", "course"],
    "real estate":    ["real estate", "proptech", "property", "broker"],
    "energy & utilities": ["energy", "solar", "utility", "renewable", "power"],
    "transportation & logistics": ["logistics", "shipping", "transport", "automotive"],
    "media & entertainment": ["media", "gaming", "music", "streaming", "content"],
}